### ISSUE TITLE
Data Unavailable

### ISSUE THREAD

**Issue by ELMIAR-0642** [1705004/Pair-EGRET#1]
Downloaded Dockground Datasets from https://dockground.compbio.ku.edu/#datasets.
> - X-ray Unbound Set 4 	396
> - X-ray Unbound Set 2 	100 x 396

But, how to load it? I set the paths properly in `config.py`.  But, cannot load the data as the following snippet at ``Pair-EGRET/data_generator_attention_visual.py``, from line 20, in ```__init__```: 
```
with gzip.open (root_dir+'/inputs/'+self.config.dataset_name+'/{}.pkl.gz'.format(data_file_prefix), 'rb') as f:
            self.dataset = pickle.load (f)
            self.protein_name_list = self.dataset[0]
            self.protein_data = self.dataset[1]  
```
could not load/find the `'{train/test/valid}.pkl.gz'` in the directory.

My questions are, 
1. How to structure the data downloaded from Dockground website in such a way that it is read by Pair_EGRET?
2. Should we prep-process it - such as extract embedddings - for these 396 proteins, before sending them as inputs?

**Comment by 1705004** [comment]
Thanks for pointing out the issue. The datasets used in this study have been uploaded to [https://zenodo.org/records/10449060](https://zenodo.org/records/10449060). I have also added the steps for regenerating the features in the Readme file. Hope this solves your issue.
